Added mmap implementation for Windows
Added mmap implementation for Windows based on MapViewOfFile. Used SliceHeader trick to change the pointer returned by MapViewOfFile to a byte slice. This will not call for any change in rest of tsm.

However I am not sure where this mmap function is called, as go build is still complains about 
    
    tsdb\engine\tsm1\tsm1.go:1974: undefined: syscall.Mmap
    tsdb\engine\tsm1\tsm1.go:1974: undefined: syscall.PROT_READ
    tsdb\engine\tsm1\tsm1.go:1974: undefined: syscall.MAP_SHARED
    tsdb\engine\tsm1\tsm1.go:2033: undefined: syscall.Munmap